"""empty message

Revision ID: 1f8483ffdfac
Revises: c558de9b0f81
Create Date: 2026-03-26 10:13:30.899113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f8483ffdfac'
down_revision: Union[str, Sequence[str], None] = 'c558de9b0f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('monthly_income', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=False),
    sa.CheckConstraint('char_length(username)>=3', name='ck_username_min_length'),
    sa.CheckConstraint('length(phone) BETWEEN 10 AND 15', name='ck_phone_length'),
    sa.CheckConstraint('monthly_income>=0', name='ck_monthly_income_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('loan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Enum('personal', 'education', 'home', 'vehicle', 'business', name='purpose'), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('employment_status', sa.Enum('employed', 'self_employed', 'unemployed', 'student', name='employmentstatus'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='status'), nullable=True),
    sa.Column('admin_remarks', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=50), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount>0 AND  amount<=1000000', name='Loan_amount_constraint'),
    sa.CheckConstraint('tenure_months>=6 and tenure_months<=360', name='check_tenure_months'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan')
    op.drop_table('user')
    # ### end Alembic commands ###
