"""empty message

Revision ID: e489e0e3b0cd
Revises: 1f8483ffdfac
Create Date: 2026-03-31 06:33:30.978668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e489e0e3b0cd'
down_revision: Union[str, Sequence[str], None] = '1f8483ffdfac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('credit_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'credit_score')
    # ### end Alembic commands ###
