"""error in  schema

Revision ID: 3486f3071357
Revises: 5f73952542b5
Create Date: 2026-03-25 13:22:21.492529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3486f3071357'
down_revision: Union[str, Sequence[str], None] = '5f73952542b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_status', sa.String(), nullable=True))
    op.drop_column('task', 'task_Status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_Status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('task', 'task_status')
    # ### end Alembic commands ###
