"""sample usage

Revision ID: fcf886b2cae9
Revises: 738c17920598
Create Date: 2026-03-25 11:46:15.052054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf886b2cae9'
down_revision: Union[str, Sequence[str], None] = '738c17920598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sample_id'), table_name='sample')
    op.drop_table('sample')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sample_pkey'))
    )
    op.create_index(op.f('ix_sample_id'), 'sample', ['id'], unique=False)
    # ### end Alembic commands ###
