# Q10. Alembic — Initialize, Migrate & Rollback

# Topics: Alembic, Database Migration, Autogenerate, Upgrade, Downgrade

# Problem Statement:

# Set up Alembic in your project to manage database migrations against your Supabase database. Perform three operations: (a) Initialize Alembic and configure it to use your DATABASE_URL from .env, (b) Generate an autogenerated migration from your User and Task models, (c) Add a new due_date column to the Task model, generate a second migration, apply it, then rollback it.

# Input (Step-by-step commands):


# # Step 1: Initialize Alembic

# alembic init alembic


# # Step 2: Configure alembic/env.py to use your models and DATABASE_URL

# # (modify env.py — see constraints below)


# # Step 3: Generate first migration

# alembic revision --autogenerate -m "create users and tasks tables"

# # Step 4: Apply migration

# alembic upgrade head


# # Step 5: Verify

# alembic current


# # Step 6: Add due_date to Task model, then:

# alembic revision --autogenerate -m "add due_date to tasks"

# alembic upgrade head


# # Step 7: Rollback the due_date migration

# alembic downgrade -1


# # Step 8: Verify rollback

# alembic current


# Output:


# # Step 3

# INFO [alembic.autogenerate.compare] Detected added table 'users'

# INFO [alembic.autogenerate.compare] Detected added table 'tasks'

# Generating alembic/versions/abc123_create_users_and_tasks_tables.py ... done


# # Step 4

# INFO [alembic.runtime.migration] Running upgrade -> abc123, create users and tasks tables


# # Step 5

# abc123 (head)


# # Step 6

# INFO [alembic.autogenerate.compare] Detected added column 'tasks.due_date'

# INFO [alembic.runtime.migration] Running upgrade abc123 -> def456, add due_date to tasks


# # Step 7

# INFO [alembic.runtime.migration] Running downgrade def456 -> abc123, add due_date to tasks

# # Step 8
# abc123

# Constraints:

# • In alembic/env.py: import your Base from models and set target_metadata = Base.metadata

# • In alembic.ini: set sqlalchemy.url to your Supabase DATABASE_URL (or load from .env in env.py)

# • due_date column: Column(DateTime, nullable=True)

# • After rollback, verify the due_date column no longer exists by querying information_schema.columns

# • Commit all migration files to version control (do NOT add them to .gitignore)

# • Each migration file must have both upgrade() and downgrade() functions






from sqlalchemy import Column, Integer, String, DateTime, ForeignKey
from sqlalchemy.orm import declarative_base, relationship

Base = declarative_base()


class Useralembic(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    email = Column(String, unique=True, nullable=False)

    tasks = relationship("Task", back_populates="user")


class Taskalembic(Base):
    __tablename__ = "tasks"

    id = Column(Integer, primary_key=True)
    title = Column(String, nullable=False)
    user_id = Column(Integer, ForeignKey("users.id"))
    due_date=Column(DateTime,nullable=False)
    user = relationship("User", back_populates="tasks")